### ISSUE TITLE
toJson method is wrong condition

### ISSUE THREAD

**Issue by Adrug** [AngelaE/ts-mountebank#12]
Hello, @AngelaE 

I found out the `body`  parameter won't never serialize for 0, "" and other false positive values.
It make hard to use [exists operator](http://www.mbtest.org/docs/api/predicates#predicates-exists)

https://github.com/AngelaE/ts-mountebank/blob/4c2314646b5da5c65ebe3fa0c520e3479a8fcc28/project/src/predicate.ts#L73

**Comment by AngelaE** [comment]
I think the above PR should fix the issue, can you have a look?

**Comment by Adrug** [comment]
Yes, I think it shoud be enough.  Thank you.
