### ISSUE TITLE
Add methods for mock verification

### ISSUE THREAD

**Issue by 4x0v7** [AngelaE/ts-mountebank#7]
As per [Mountebank docs](https://www.mbtest.org/docs/api/mocks) it would be nice to allow mock verification as part of this project.

Perhaps another method on the `Imposter` Class could be created, something like `withMockVerification` which would set `recordRequests: true` when creating the Imposter

**Comment by AngelaE** [comment]
That sounds like a good idea. I am currently splitting the integration tests out and have some changes in the master branch already => Feel free to create a PR.
I am planning to publish a new version after I get #6 merged.

This is a total side project and right now the github actions are taking me a bit to get used to...

**Comment by 4x0v7** [comment]
Haha integration tests for an integration testing tool 😄
No worries it's a pretty new project! Thanks for making this btw 😃

**Comment by AngelaE** [comment]
Check out whether it works for you. You can now also query the imposter from MB.
